"""Build Fig 4a — PSD + FOOOF fit per dataset.

Usage (from repo root):
    python -m reproduction.builders.fig4a_psd_fooof

1×4 panel strip (EEGMAT / SleepDep / Stress / ADFTD). Each panel shows the
mean log-PSD of the highest-quality recording with the aperiodic 1/f fit
overlaid (dashed) and the periodic peaks shaded.

Shared bottom legend (PSD / aperiodic fit / periodic peaks) — matches the
Fig 4 convention (`fig.legend(loc="lower center", ncol=3, frameon=False)`).

Output: paper/figures/fig5/fig4a_psd_fooof_fit.{pdf,png}
"""
from __future__ import annotations
import sys
from pathlib import Path

from reproduction.builders._runtime import output_dir, paper_data_path
# fmscope is pip-installed; no sys.path hacks needed
# fmscope is pip-installed; no sys.path hacks needed

import matplotlib as mpl  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from scipy.signal import welch  # noqa: E402

from reproduction.builders import results_accessor as results  # noqa: E402
from reproduction.builders._style import apply_jne_style, JNE_DOUBLE_COL_CM, CM  # noqa: E402

OUT = output_dir("paper_figures")
OUT.mkdir(parents=True, exist_ok=True)

apply_jne_style()

W_DOUBLE = JNE_DOUBLE_COL_CM * CM

DS_PSD = ["eegmat", "sleepdep", "stress", "adftd"]
DS_SHORT = {"eegmat": "EEGMAT", "sleepdep": "SleepDep",
            "stress": "Stress", "adftd": "ADFTD"}

SFREQ = 200
FMIN, FMAX = 1, 50


def mean_psd(sig: np.ndarray):
    s = sig.reshape(-1, sig.shape[-1])
    f, P = welch(s, fs=SFREQ, nperseg=min(512, s.shape[-1]), axis=-1)
    m = (f >= FMIN) & (f <= FMAX)
    return f[m], P.mean(axis=0)[m]


def rep_psd(ds: str) -> dict:
    """Aggregate PSD + aperiodic fit for the highest-quality recording.

    The public release reads pre-computed curves from a bundled JSON
    (``reproduction/data/fig4a_psd_cache``) because the raw FOOOF-ablated
    feature caches are ~5 GB and not redistributed. The cache was
    generated by the original fig4a code against the collaboration-only
    feature caches; regenerate via ``scripts/build_fig4a_psd_cache.py``
    if you have access to the raw NPZs.
    """
    import json as _json

    cache_path = paper_data_path("fig4a_psd_cache.json")
    if cache_path.exists():
        cache = _json.loads(cache_path.read_text())
        d = cache[ds]
        return dict(
            f=np.array(d["f"]),
            ap=np.array(d["ap"]),
            pe=np.array(d["pe"]),
            fit=np.array(d["fit"]),
            chi=d["chi"],
        )

    # Fallback: compute on the fly from raw NPZs (collaboration-only).
    p = results.fooof_ablated_features_path(ds, w5=(ds == "adftd"))
    d = np.load(p, allow_pickle=True)
    ri = int(d["quality_r2"].mean(axis=1).argmax())
    mask = d["window_rec_idx"] == ri
    f, P_ap = mean_psd(d["periodic_removed"][mask])
    _, P_pe = mean_psd(d["aperiodic_removed"][mask])
    b = float(d["aperiodic_b"][ri].mean())
    chi = float(d["aperiodic_chi"][ri].mean())
    return dict(f=f, ap=P_ap, pe=P_pe, fit=10 ** b / (f ** chi), chi=chi)


def main() -> None:
    psd = {ds: rep_psd(ds) for ds in DS_PSD}

    fig, axes = plt.subplots(1, len(DS_PSD),
                             figsize=(W_DOUBLE, W_DOUBLE * 0.32),
                             sharey=False)
    for ax, ds in zip(axes, DS_PSD):
        d = psd[ds]
        ax.loglog(d["f"], d["ap"] + d["pe"], color="#222", lw=1.4, label="PSD")
        ax.loglog(d["f"], d["fit"], color="#D55E00", ls="--", lw=1.1,
                  label="aperiodic fit")
        ax.fill_between(d["f"], d["fit"], d["fit"] + d["pe"],
                        color="#0072B2", alpha=0.28, label="periodic peaks")
        ax.set_xlabel("Freq (Hz)", fontsize=8)
        ax.set_title(DS_SHORT[ds], fontsize=10)
        ax.tick_params(labelsize=7.5)
        ax.grid(True, which="both", ls=":", lw=0.3, alpha=0.5)
    axes[0].set_ylabel(r"PSD ($\mu$V$^2$/Hz)", fontsize=8.5)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3,
               fontsize=8, frameon=False, bbox_to_anchor=(0.5, 0.04),
               handlelength=1.2, handletextpad=0.5, columnspacing=2.0)

    plt.tight_layout(rect=[0, 0.10, 1, 1])
    for ext in ("pdf", "png"):
        fig.savefig(OUT / f"fig4a_psd_fooof_fit.{ext}")
    plt.close(fig)
    print(f"wrote fig4a_psd_fooof_fit.{{pdf,png}} → {OUT.name}")


if __name__ == "__main__":
    main()
