"""Regenerate ``docs/master_results_table.md`` from canonical sources.

Single source of truth: ``results/final/`` via ``src.results``. Run after any
canonical refresh. Idempotent — same canonical input produces byte-identical
output.

Usage:
    python scripts/analysis/build_master_results_table.py
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

from reproduction.builders import results_accessor as results
from reproduction.builders._runtime import output_dir, paper_data_path

CELLS = [
    ("stress", "Stress (DASS)", "70 / 17", "per-recording DASS binary (14/17 subjects consistent)", "subject-trait × no-prior-marker"),
    ("adftd", "ADFTD", "65 / 65 (split1, AD=36 / HC=29)", "subject-level AD vs HC binary", "subject-trait × prior-marker (1/f aperiodic-slope prior [Donoghue'20; Babiloni'21])"),
    ("sleepdep", "SleepDep", "72 / 36", "within-subject rested vs SD", "within-subject paired × no-prior-marker"),
    ("eegmat", "EEGMAT", "72 / 36", "within-subject rest vs arithmetic", "within-subject paired × prior-marker (FMT + parieto-occipital α [Klimesch'99; Gevins'97])"),
]

FMS = ["labram", "cbramod", "reve"]

FT_HP = {
    "labram": "lr=5e-4, layer_decay=0.65, wd=0.05, CE+LS 0.1, norm=none (post-2026-04-27 alignment)",
    "cbramod": "backbone lr=1e-4 / head lr=5e-4, wd=0.05, CE+LS 0.1, norm=none",
    "reve": "max_lr=2.4e-4, encoder_lr_scale=0.1, wd=0.01, warmup 2ep, norm=none, window=5s",
}

NONFM_ARCHS = ["eegnet", "shallowconvnet", "deepconvnet", "eegconformer"]
CLASSICAL_MODELS = ["LogReg_L2", "LogReg_L1", "SVM_RBF", "RF", "XGBoost"]


def fmt(mean: float | None, std: float | None) -> str:
    if mean is None:
        return "—"
    if std is None:
        return f"{mean:.3f}"
    return f"{mean:.3f} ± {std:.3f}"


def load_classical(cell: str) -> dict[str, tuple[float, float]]:
    p = paper_data_path(cell, "classical", "summary.json")
    if not p.exists():
        return {}
    j = json.loads(p.read_text())
    out = {}
    for model, stats in j.get("aggregated", {}).items():
        out[model] = (stats["mean_bal_acc"], stats.get("std_bal_acc"))
    return out


def load_nonfm_deep(cell: str) -> dict[str, tuple[float, float]]:
    out = {}
    for arch in NONFM_ARCHS:
        d = paper_data_path(cell, "nonfm_deep", arch)
        if not d.exists():
            continue
        bas = []
        for sd in sorted(d.glob("seed*/summary.json")):
            j = json.loads(sd.read_text())
            ba = j.get("subject_bal_acc")
            if ba is not None:
                bas.append(float(ba))
        if bas:
            mean = sum(bas) / len(bas)
            std = statistics.stdev(bas) if len(bas) > 1 else 0.0
            out[arch] = (mean, std)
    return out


def render() -> str:
    lines = []
    lines.append("# Master Results Table")
    lines.append("")
    lines.append("Auto-regenerated by `scripts/analysis/build_master_results_table.py` from `results/final/` via `src.results` accessor. Single source of truth — re-run after any canonical refresh.")
    lines.append("")
    lines.append("All BA = subject-level 5-fold CV, 3 seeds (42, 123, 2024). Sample std (ddof=1).")
    lines.append("")

    for cell, name, n, label, regime in CELLS:
        lines.append(f"## {name}")
        lines.append(f"- Recordings / Subjects: **{n}**")
        lines.append(f"- Label: {label}")
        lines.append(f"- Cell: *{regime}*")
        lines.append("")

        # FM LP / FT table
        lines.append("| FM | LP (frozen) | FT | FT HP (per-FM canonical, G-F09) |")
        lines.append("|---|---|---|---|")
        for fm in FMS:
            lp = results.lp_stats_3seed(cell, fm) or {}
            ft = results.ft_stats(cell, fm) or {}
            lp_str = fmt(lp.get("mean"), lp.get("std"))
            ft_str = fmt(ft.get("mean"), ft.get("std"))
            lines.append(f"| {fm} | {lp_str} | {ft_str} | {FT_HP[fm]} |")
        lines.append("")
        lines.append(f"> Source: `results/final/{cell}/{{lp,ft}}/<fm>...` via `src.results.lp_stats_3seed` / `ft_stats` (post-2026-04-27 alignment refresh).")
        lines.append("")

        # Classical
        cls = load_classical(cell)
        if cls:
            lines.append("**Classical ML** (per-rec features, 3 seeds, class-balanced):")
            lines.append("")
            lines.append("| Model | BA |")
            lines.append("|---|---|")
            for m in CLASSICAL_MODELS:
                if m in cls:
                    lines.append(f"| {m} | {fmt(*cls[m])} |")
            lines.append("")

        # Non-FM deep
        nonfm = load_nonfm_deep(cell)
        if nonfm:
            lines.append("**Non-FM deep** (from-scratch, 3 seeds):")
            lines.append("")
            lines.append("| Arch | BA |")
            lines.append("|---|---|")
            for arch in NONFM_ARCHS:
                if arch in nonfm:
                    lines.append(f"| {arch} | {fmt(*nonfm[arch])} |")
            lines.append("")

    # 2×2 quick-view
    lines.append("---")
    lines.append("## 2×2 quick-view (subject-level BA, 3-seed mean ± std)")
    lines.append("")
    lines.append("| Dataset | Cell | n_rec / n_subj | LaBraM LP | LaBraM FT | CBraMod LP | CBraMod FT | REVE LP | REVE FT | Classical best | Non-FM best |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for cell, name, n, _label, regime in CELLS:
        row_vals = []
        for fm in FMS:
            lp = results.lp_stats_3seed(cell, fm) or {}
            ft = results.ft_stats(cell, fm) or {}
            row_vals.append(fmt(lp.get("mean"), lp.get("std")))
            row_vals.append(fmt(ft.get("mean"), ft.get("std")))
        cls = load_classical(cell)
        if cls:
            best_cls = max(cls.items(), key=lambda kv: kv[1][0])
            cls_str = f"{best_cls[0]} {fmt(*best_cls[1])}"
        else:
            cls_str = "—"
        nonfm = load_nonfm_deep(cell)
        if nonfm:
            best_nf = max(nonfm.items(), key=lambda kv: kv[1][0])
            nf_str = f"{best_nf[0]} {fmt(*best_nf[1])}"
        else:
            nf_str = "—"
        lines.append(f"| {name} | {regime.split(' (')[0]} | {n.split(' (')[0]} | " + " | ".join(row_vals) + f" | {cls_str} | {nf_str} |")
    lines.append("")
    lines.append(f"> All numbers regenerated via `scripts/analysis/build_master_results_table.py` from canonical `results/final/`. Re-run this script after any seed-level rerun in `results/final/<cell>/{{ft,lp,classical,nonfm_deep}}/`.")
    lines.append("")
    return "\n".join(lines)


def render_tex() -> str:
    """Render Tab 2 (master performance) as a body-only LaTeX table.

    Rows = 10 methods grouped into 3 tiers (Non-FM deep / FM linear probe /
    FM full fine-tune), each tier preceded by a multicolumn group header.
    Classical ML baselines are intentionally omitted from the paper table to
    keep the comparison focused on architecture-level claims (FM vs from-
    scratch deep); they remain in the markdown reference dump
    (``docs/master_results_table.md``).
    Columns = 4 datasets in 2×2 order (prior-marker column first, within-
    subject paired before subject-trait within each column).
    Bolds the column-best within each tier × dataset block.
    """
    tex_order = ["eegmat", "adftd", "sleepdep", "stress"]
    cell_lookup = {c[0]: c for c in CELLS}

    nonfm_labels = {
        "eegnet": "EEGNet", "shallowconvnet": "ShallowConvNet",
        "deepconvnet": "DeepConvNet", "eegconformer": "EEGConformer",
    }
    fm_labels = {"labram": "LaBraM", "cbramod": "CBraMod", "reve": "REVE"}

    def fmt_tex(val, bold=False):
        if val is None or val[0] is None:
            return "---"
        mean, std = val
        body = f"{mean:.3f}"
        if std is not None:
            body = f"{mean:.3f}{{\\scriptsize\\,$\\pm$\\,{std:.3f}}}"
        if bold:
            body = f"\\textbf{{{body}}}"
        return body

    def best_idx(values):
        idx, best = None, -1.0
        for i, v in enumerate(values):
            if v is None or v[0] is None:
                continue
            if v[0] > best:
                idx, best = i, v[0]
        return idx

    # Collect per-cell (mean, std) tuples for each method.
    per_cell = {}
    for cell in tex_order:
        nonfm = load_nonfm_deep(cell)
        per_cell[cell] = {
            "nonfm": [nonfm.get(a) for a in NONFM_ARCHS],
            "lp": [
                ((d := results.lp_stats_3seed(cell, fm) or {}).get("mean"), d.get("std"))
                if (results.lp_stats_3seed(cell, fm) or {}).get("mean") is not None else None
                for fm in FMS
            ],
            "ft": [
                ((d := results.ft_stats(cell, fm) or {}).get("mean"), d.get("std"))
                if (results.ft_stats(cell, fm) or {}).get("mean") is not None else None
                for fm in FMS
            ],
        }

    # Per-tier column-bests (one best index per dataset per tier).
    bests = {tier: {cell: best_idx(per_cell[cell][tier]) for cell in tex_order}
             for tier in ("nonfm", "lp", "ft")}

    def tier_rows(tier_key, model_keys, label_map):
        out = []
        for i, mk in enumerate(model_keys):
            row = [label_map[mk]]
            for cell in tex_order:
                v = per_cell[cell][tier_key][i]
                row.append(fmt_tex(v, bold=(bests[tier_key][cell] == i)))
            out.append(" & ".join(row) + " \\\\")
        return out

    def regime_tag(cell):
        _, _, _, _, regime = cell_lookup[cell]
        if "within-subject paired" in regime and "no-prior" in regime:
            return "within$\\times$no-prior"
        if "within-subject paired" in regime:
            return "within$\\times$prior"
        if "no-prior" in regime:
            return "trait$\\times$no-prior"
        return "trait$\\times$prior"

    name_lookup = {c[0]: c[1] for c in CELLS}
    name_lookup["stress"] = "Stress"  # tighten header
    header_main = " & ".join(f"\\textbf{{{name_lookup[c]}}}" for c in tex_order)
    header_tag = " & ".join(f"{{\\scriptsize\\textit{{{regime_tag(c)}}}}}" for c in tex_order)

    nfm_rows = tier_rows("nonfm", NONFM_ARCHS, nonfm_labels)
    lp_rows = tier_rows("lp", FMS, fm_labels)
    ft_rows = tier_rows("ft", FMS, fm_labels)

    body_lines = []
    body_lines.append("\\multicolumn{5}{l}{\\textit{Non-FM deep} (from-scratch on raw EEG)} \\\\")
    body_lines.extend(nfm_rows)
    body_lines.append("\\midrule")
    body_lines.append("\\multicolumn{5}{l}{\\textit{FM linear probe} (frozen per-window features)} \\\\")
    body_lines.extend(lp_rows)
    body_lines.append("\\midrule")
    body_lines.append("\\multicolumn{5}{l}{\\textit{FM full fine-tune} (per-FM canonical recipe, Sec.~\\ref{sec:methods_ft})} \\\\")
    body_lines.extend(ft_rows)
    body = "\n".join(body_lines)

    return rf"""% Tab 1 — Master performance landscape (body only)
% Auto-generated by scripts/analysis/build_master_results_table.py
% from canonical results/final/ via src.results. Do NOT edit by hand.
% Standalone preview: paper/tables/main/table2_master_performance_standalone.tex
\begin{{table}}[htbp]
\centering
\small
\setlength{{\tabcolsep}}{{6pt}}
\caption{{\textbf{{Subject-disjoint 5-fold CV balanced accuracy across the 2$\times$2 factorial.}}
Methods (rows) are grouped into three tiers: non-FM deep models trained from scratch on raw EEG (EEGNet, ShallowConvNet, DeepConvNet, EEGConformer); FM linear probe (LP) on frozen per-window features; and FM full fine-tuning (FT) under each backbone's canonical recipe (Methods Sec.~\ref{{sec:methods_ft}}).
Datasets (columns) are arranged by 2$\times$2 cell (prior cross-subject marker column first; within-subject paired row first within each column).
All values are subject-disjoint balanced accuracy, 3-seed mean with sample std (ddof=1) in subscript; seeds $\{{42, 123, 2024\}}$.
\textbf{{Bold}} marks the column-best within each tier $\times$ dataset block.
Classical ML baselines (logistic regression, SVM-RBF, random forest, XGBoost on per-recording band-power features) are reported in the supplementary results dump (\texttt{{docs/master\_results\_table.md}}) and omitted here to keep the comparison focused on architecture-level claims.
Dataset sizes: EEGMAT 72\,rec / 36\,subj; ADFTD 65 / 65 (split1, AD=36 / HC=29); SleepDep 72 / 36; Stress 70 / 17.
Numbers regenerated from \texttt{{results/final/}} via \texttt{{scripts/analysis/build\_master\_results\_table.py}}; do not edit by hand.}}
\label{{tab:master_performance}}
\begin{{tabular}}{{l cccc}}
\toprule
\textbf{{Method}} & {header_main} \\
 & {header_tag} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def main():
    out = output_dir("paper_tables") / "master_results_table.md"
    text = render()
    out.write_text(text)
    print(f"Wrote {out}  ({len(text.splitlines())} lines)")

    out_tex = output_dir("paper_tables") / "table2_master_performance.tex"
    tex = render_tex()
    out_tex.write_text(tex)
    print(f"Wrote {out_tex}  ({len(tex.splitlines())} lines)")


if __name__ == "__main__":
    main()
